### ISSUE TITLE
When Steam Controller sleeps CPU goes up to 100%

### ISSUE THREAD

**Issue by saynotocode** [Alia5/GlosSI#125] opened 2021-02-22 05:56 UTC
I have a steam controller which i primarily use for Rocket League. After Epic took ownership of RL it messed up the controller configs for the steam version a bit. To get around this i started using GLOSC to enable better SC configs. I've been using GLOSC this way since October 2020.

My issue is that if I open RL with the GLOSC shortcut in steam it works fine, but if I leave the game running and walk away long enough for the Steam Controller to switch off (set to 10 minutes) then the PC becomes unresponsive. Task manager shows 100% CPU usage and windows cannot be interacted with. Attempts to open the Details tab of task manager just never seem to get there. Sometimes a popup will appear saying 'This program is unresponsive. Would you like to close it.' The popup title is Microsoft Windows so I'm never sure what process is being ended. This will kill some processes, including explorer, so the desktop can go away at times. This can go on for several minutes but each time i cannot regain control of the PC and end up doing a hard reset by holding the power button down. CTRL-ALT-DEL doesn't help either.

This only started happening recently, I think after upgrading win10 to 20H2 about two weeks ago. If i start Rocket League from steam with a non-GLOSC shortcut this issue doesn't appear at all.

The PC is a desktop I5 6600K, 32GB DDR4, GTX 970, NVME SSD (system drive), 3x2TB HDDS arranged into three separate storage space volumes. Game files are on one of the storage space drives.

**Comment by saynotocode** [comment] 2021-02-22 06:08
Just want to add .. this is happening with the steam version of Rocket League.

**Comment by Alia5** [comment] 2021-10-30 14:20
Cannot reproduce with GlosSI  
Duplicate of #92

**Closed by Alia5** 2021-10-30 14:20 UTC
Labels: Legacy
